---
name: Checks  

on: [push]

jobs:
  Test:
    name: UnitTest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: python manage.py test  