---
name: Checks  

on: [push]

jobs:
  Test:
    name: UnitTest
    runs-on: ubuntu-20.04
    steps:
      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: python manage.py test